version: '3.8'

services:
  ubuntu-gui-l2tp:
    build:
      context: .
    container_name: ubuntu-gui-l2tp
    ports:
      - "5901:5901"
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro